### ISSUE TITLE
work manager failing

### ISSUE THREAD

**Issue by justinklchan** [covidsafe/App-Android#88]
2020-05-02 01:43:53.696 24718-24718/edu.uw.covidsafe E/AndroidRuntime: FATAL EXCEPTION: main
    Process: edu.uw.covidsafe, PID: 24718
    java.lang.RuntimeException: Unable to start service edu.uw.covidsafe.service.LoggingService@2c60144 with Intent { cmp=edu.uw.covidsafe/.service.LoggingService }: java.lang.ClassCastException: edu.uw.covidsafe.CovidSafeApplication cannot be cast to androidx.lifecycle.LifecycleOwner
        at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:4306)
        at android.app.ActivityThread.access$1900(ActivityThread.java:268)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2014)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:237)
        at android.app.ActivityThread.main(ActivityThread.java:7811)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1076)
     Caused by: java.lang.ClassCastException: edu.uw.covidsafe.CovidSafeApplication cannot be cast to androidx.lifecycle.LifecycleOwner
        at edu.uw.covidsafe.ble.BluetoothUtils.startBle(BluetoothUtils.java:167)
        at edu.uw.covidsafe.service.LoggingService.performLoggingWork(LoggingService.java:57)
        at edu.uw.covidsafe.service.LoggingService.onStartCommand(LoggingService.java:47)
        at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:4288)
        at android.app.ActivityThread.access$1900(ActivityThread.java:268) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2014) 
        at android.os.Handler.dispatchMessage(Handler.java:107) 
        at android.os.Looper.loop(Looper.java:237) 
        at android.app.ActivityThread.main(ActivityThread.java:7811) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1076)

**Comment by aakash1313** [comment]
https://github.com/covidsafe/App-Android/commit/2fb0d7ecd25c342c253549fb2fde1c0befb301fe

This one fixes it
