### ISSUE TITLE
Crash on Import Location History Fragment

### ISSUE THREAD

**Issue by aakash1313** [covidsafe/App-Android#90]
at android.app.LoadedApk$ReceiverDispatcher.<init>(LoadedApk.java:1548)
        at android.app.LoadedApk.getReceiverDispatcher(LoadedApk.java:1280)
        at android.app.ContextImpl.registerReceiverInternal(ContextImpl.java:1555)
        at android.app.ContextImpl.registerReceiver(ContextImpl.java:1528)
        at android.app.ContextImpl.registerReceiver(ContextImpl.java:1516)
        at android.content.ContextWrapper.registerReceiver(ContextWrapper.java:636)
        at edu.uw.covidsafe.gps.ImportLocationHistoryFragment.onCreateView(ImportLocationHistoryFragment.java:85)
        at androidx.fragment.app.Fragment.performCreateView(Fragment.java:2698)
        at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:310)

**Comment by aakash1313** [comment]
@justinklchan : https://github.com/covidsafe/App-Android/commit/dba10e746f127eeedfde94d93

**Comment by aakash1313** [comment]
@justinklchan : even this one is fixed partially by me and completely by you :)
